const crypto = require('crypto');

// Minimal .env parser: KEY=VALUE lines, '#' comments and blank lines ignored,
// surrounding single/double quotes stripped.
function parseEnvValues(text) {
  const values = {};
  for (const rawLine of text.split('\n')) {
    const line = rawLine.trim();
    if (!line || line.startsWith('#')) continue;
    const idx = line.indexOf('=');
    if (idx === -1) continue;
    const key = line.slice(0, idx).trim();
    let value = line.slice(idx + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"') && value.length >= 2) ||
      (value.startsWith("'") && value.endsWith("'") && value.length >= 2)
    ) {
      value = value.slice(1, -1);
    }
    values[key] = value;
  }
  return values;
}

// Renders a full .env file from the var definitions (in scripts/deploy.js) and
// a values map, with each var's prompt/help text as a leading comment. The
// script owns .env's structure entirely rather than trying to preserve
// hand-edits, which keeps this simple and matches .env.example's shape.
function renderEnvFile(varDefs, values) {
  const lines = ['# Generated by scripts/deploy.js — local only, never commit this file.', ''];
  for (const def of varDefs) {
    const value = values[def.key] ?? '';
    lines.push(`# ${def.prompt}`);
    if (def.help) lines.push(`# ${def.help}`);
    // Values are expected to be single-line (e.g. GOOGLE_PRIVATE_KEY is stored
    // with literal \n escapes, not real newlines — functions/_lib/sheets.js
    // unescapes it at read time). Quote only to protect leading/trailing
    // whitespace; no JSON escaping, so quoting stays a plain, reversible wrap.
    const needsQuotes = /^\s|\s$/.test(value);
    lines.push(`${def.key}=${needsQuotes ? `"${value}"` : value}`);
    lines.push('');
  }
  return lines.join('\n').replace(/\n{3,}/g, '\n\n').trimEnd() + '\n';
}

// A blank answer keeps whatever was already in .env; if there's nothing to
// keep and the var supports it, a random value is generated instead of
// leaving it empty (used for the shared trigger-send secret).
function resolveValue(def, existingValue, answer) {
  const trimmed = (answer || '').trim();
  if (trimmed) return trimmed;
  if (existingValue) return existingValue;
  if (def.autoGenerate) return crypto.randomBytes(24).toString('hex');
  return '';
}

module.exports = { parseEnvValues, renderEnvFile, resolveValue };
